title:              Bit by Bit
email:              bhavnakandra1412@gmail.com
description:        Data Science Research Blogs
author:             Bhavna Kandra
baseurl:            "/ds-research-blogs"
url:                "https://bittyowlett.github.io"

# Social Profiles
twitter_username:   
github_username:    bittyowlett
facebook_username:  
instagram_username:  
linkedin_username: /in/bhavna-kandra

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
